services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - experementarium
    container_name: experementarium_nginx

  experementarium:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: experementarium

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: experementarium
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    container_name: experementarium_db
