services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - exp
        container_name: exp_nginx

    exp:
        build:
            context: .
            dockerfile: ./_docker/app/Dockerfile
        ports:
            - 5173:5173
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        container_name: exp

    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: experimentarium
            POSTGRES_PASSWORD: password
        ports:
            - 5433:5432
        container_name: exp_db
